version: '3.8'

services:
  api:
    build: ./src
    command: |
     sh -c 'while ! nc -z db 5432; do sleep 1; done; python3 -m uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080'
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=postgresql://postgres_user:postgres_pw@db/mindmap
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pw
      - POSTGRES_DB=mindmap

volumes:
  postgres_data: